[project]
name = "luminous-schema-engine2"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/luminous-schema-engine2/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.luminous-schema-engine2]
path = "contracts/luminous-schema-engine2.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
